# Generated by Django 4.2.23 on 2025-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('training', 'Training Certificate'), ('equipment', 'Equipment Certificate')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('sticker_no', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
