# Generated by Django 5.2.3 on 2025-06-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_type',
        ),
    ]
